### ISSUE TITLE
PyDevD from pip not working on Windows with PyCharm

### ISSUE THREAD

**Issue by apahim** [fabioz/PyDev.Debugger#116]
Version:
```
$ pip show pydevd
Name: pydevd
Version: 1.3.2
Summary: PyDev.Debugger (used in PyDev, PyCharm and VSCode Python)
Home-page: https://github.com/fabioz/PyDev.Debugger/
Author: Fabio Zadrozny and others
Author-email: UNKNOWN
License: EPL (Eclipse Public License)
Location: c:\users\apahim\appdata\local\programs\python\python36\lib\site-packages
Requires:
Required-by:
```

Test code:
```python
def test(a):
    import pydevd
    pydevd.settrace()
    return a

test(10)
```

Debug:
```
$ PYCHARM_DEBUG=True python test.py
Using Cython speedups
PYDEVD_FILTER_LIBRARIES False

('Connecting to ', 'localhost', ':', '5678')
('Connected.',)
debugger: received >>501        1       0.1     WIN
<<
Received command: CMD_VERSION 501       1       0.1     WIN

Traceback (most recent call last):
  File "c:\users\apahim\appdata\local\programs\python\python36\lib\site-packages\_pydevd_bundle\pydevd_process_net_command.py", line 74, in process_net_command
    pydevd_file_utils.set_ide_os(ide_os)
  File "c:\users\apahim\appdata\local\programs\python\python36\lib\site-packages\pydevd_file_utils.py", line 171, in set_ide_os
    assert os in ('WINDOWS', 'UNIX')
AssertionError
Error: Unexpected exception in process_net_command.
```

Server output (PyCharm):
```
Starting debug server at port 5678
Use the following code to connect to the debugger:
import pydevd
pydevd.settrace('localhost', port=5678, stdoutToServer=True, stderrToServer=True)
Waiting for process connection...
Server stopped.
Disconnected
```

Workaround:
```diff
diff --git a/pydevd_file_utils.py b/pydevd_file_utils.py
index 48074d4..2544a57 100644
--- a/pydevd_file_utils.py
+++ b/pydevd_file_utils.py
@@ -189,7 +189,7 @@ def set_ide_os(os):
     :param os:
         'UNIX' or 'WINDOWS'
     '''
-    assert os in ('WINDOWS', 'UNIX')
+    assert os in ('WINDOWS', 'UNIX', 'WIN')

     global _ide_os
     _ide_os = os
```

**Comment by fabioz** [comment]
I've already fixed this in the repo. Thanks for the report.

**Comment by fabioz** [comment]
Already fixed. Thanks for the report.
