### ISSUE TITLE
_NormPaths causing issue on unicodes

### ISSUE THREAD

**Issue by Wilhelmsson177** [fabioz/PyDev.Debugger#126]
Hello,

after the latest PyDev update in eclipse to version 6.5.0.201809011628. I have been noticing a strange behavior on `def _NormPaths(filename):` in PyDev.Debugger/pydevd_file_utils.py.

The check for the str always raises an AssertionError, because a unicode is detected instead. If i comment out the following lines, everything works fine in my case.

```python
if filename.__class__ != str:
    raise AssertionError('Paths passed to _NormPaths must be str. Found: %s (%s)' % (filename, type(filename)))
````

These two lines are causing the following output for a lot of files when I try to attach to my process, it becomes not responsive anymore.

```logfile
AssertionError: Paths passed to _NormPaths must be str. Found: C:\Development\project\application\gui\FrmMain.pyo (<type 'unicode'>)
AssertionError: Paths passed to _NormPaths must be str. Found: C:\Development\project\lib\FileMonitor.pyo (<type 'unicode'>)
Traceback (most recent call last):
Traceback (most recent call last):
  File "_pydevd_bundle\pydevd_cython_win32_27_64.pyx", line 1230, in _pydevd_bundle.pydevd_cython_win32_27_64.ThreadTracer.__call__
  File "_pydevd_bundle\pydevd_cython_win32_27_64.pyx", line 1230, in _pydevd_bundle.pydevd_cython_win32_27_64.ThreadTracer.__call__
  File "C:/Users/Willi/.p2/pool/plugins/org.python.pydev.core_6.5.0.201809011628/pysrc\pydevd_file_utils.py", line 525, in get_abs_path_real_path_and_base_from_frame
  File "C:/Users/Willi/.p2/pool/plugins/org.python.pydev.core_6.5.0.201809011628/pysrc\pydevd_file_utils.py", line 525, in get_abs_path_real_path_and_base_from_frame
  File "C:/Users/Willi/.p2/pool/plugins/org.python.pydev.core_6.5.0.201809011628/pysrc\pydevd_file_utils.py", line 503, in get_abs_path_real_path_and_base_from_file
  File "C:/Users/Willi/.p2/pool/plugins/org.python.pydev.core_6.5.0.201809011628/pysrc\pydevd_file_utils.py", line 503, in get_abs_path_real_path_and_base_from_file
  File "C:/Users/Willi/.p2/pool/plugins/org.python.pydev.core_6.5.0.201809011628/pysrc\pydevd_file_utils.py", line 337, in _NormPaths
  File "C:/Users/Willi/.p2/pool/plugins/org.python.pydev.core_6.5.0.201809011628/pysrc\pydevd_file_utils.py", line 337, in _NormPaths
  File "C:/Users/Willi/.p2/pool/plugins/org.python.pydev.core_6.5.0.201809011628/pysrc\pydevd_file_utils.py", line 224, in _NormPaths
  File "C:/Users/Willi/.p2/pool/plugins/org.python.pydev.core_6.5.0.201809011628/pysrc\pydevd_file_utils.py", line 224, in _NormPaths
```

It was working fine with the version before. I don't know if the issue has some other source. If you need any help identifying the issue, please let me know.

**Comment by fabioz** [comment]
This is odd and shouldn't be happening (ThreadTracer uses `frame.f_code.co_filename` and that should be bytes in Python 2, not unicode -- there's only one place in `_pydevd_bundle.pydevd_trace_dispatch_regular.ThreadTracer.__call__` which calls `get_abs_path_real_path_and_base_from_frame` and it uses `frame.f_code.co_filename`, so, I'm really puzzled on how that happens and I can't reproduce it here).

You're using the cythonized version of that code from `_pydevd_bundle.pydevd_cython_win32_27_64.pyd` -- if you rename that file to something else, do you get the same stack trace? 

Do you know if there's anything particular to your Python installation or something else which could make `frame.f_code.co_filename` be a unicode?

**Comment by Wilhelmsson177** [comment]
Hey @fabioz,

I'm debugging ECU-TEST a tool by TraceTronic, which is also a Gold Sponsor of PyDev. 

Traceback when .pyd is removed:
```
Traceback (most recent call last):
AssertionError: Paths passed to _NormPaths must be str. Found: C:\Development\project\threading.pyo (<type 'unicode'>)
  File "C:/Users/Willi/.p2/pool/plugins/org.python.pydev.core_6.5.0.201809011628/pysrc\pydevd_file_utils.py", line 525, in get_abs_path_real_path_and_base_from_frame
Traceback (most recent call last):
  File "C:/Users/Willi/.p2/pool/plugins/org.python.pydev.core_6.5.0.201809011628/pysrc\pydevd_file_utils.py", line 503, in get_abs_path_real_path_and_base_from_file
  File "C:/Users/Willi/.p2/pool/plugins/org.python.pydev.core_6.5.0.201809011628/pysrc\_pydevd_bundle\pydevd_trace_dispatch_regular.py", line 282, in __call__
  File "C:/Users/Willi/.p2/pool/plugins/org.python.pydev.core_6.5.0.201809011628/pysrc\pydevd_file_utils.py", line 503, in get_abs_path_real_path_and_base_from_file
Traceback (most recent call last):
  File "C:/Users/Willi/.p2/pool/plugins/org.python.pydev.core_6.5.0.201809011628/pysrc\_pydevd_bundle\pydevd_trace_dispatch_regular.py", line 282, in __call__
  File "C:/Users/Willi/.p2/pool/plugins/org.python.pydev.core_6.5.0.201809011628/pysrc\pydevd_file_utils.py", line 337, in _NormPaths
  File "C:/Users/Willi/.p2/pool/plugins/org.python.pydev.core_6.5.0.201809011628/pysrc\pydevd_file_utils.py", line 525, in get_abs_path_real_path_and_base_from_frame
  File "C:/Users/Willi/.p2/pool/plugins/org.python.pydev.core_6.5.0.201809011628/pysrc\pydevd_file_utils.py", line 337, in _NormPaths
  File "C:/Users/Willi/.p2/pool/plugins/org.python.pydev.core_6.5.0.201809011628/pysrc\_pydevd_bundle\pydevd_trace_dispatch_regular.py", line 282, in __call__
  File "C:/Users/Willi/.p2/pool/plugins/org.python.pydev.core_6.5.0.201809011628/pysrc\pydevd_file_utils.py", line 525, in get_abs_path_real_path_and_base_from_frame
  File "C:/Users/Willi/.p2/pool/plugins/org.python.pydev.core_6.5.0.201809011628/pysrc\pydevd_file_utils.py", line 224, in _NormPaths
  File "C:/Users/Willi/.p2/pool/plugins/org.python.pydev.core_6.5.0.201809011628/pysrc\pydevd_file_utils.py", line 503, in get_abs_path_real_path_and_base_from_file
  File "C:/Users/Willi/.p2/pool/plugins/org.python.pydev.core_6.5.0.201809011628/pysrc\pydevd_file_utils.py", line 224, in _NormPaths
  File "C:/Users/Willi/.p2/pool/plugins/org.python.pydev.core_6.5.0.201809011628/pysrc\pydevd_file_utils.py", line 525, in get_abs_path_real_path_and_base_from_frame
  File "C:/Users/Willi/.p2/pool/plugins/org.python.pydev.core_6.5.0.201809011628/pysrc\pydevd_file_utils.py", line 503, in get_abs_path_real_path_and_base_from_file
```

The check returns: `<type 'str'>`.

This whole thing is really strange. I checked with a colleague and he did not have this issue using the newest version and attaching to the same tool.

If you have another idea, please let me know, but don't put to much effort into it. 

I'm very excited that the extension for VSCode will continue.
