### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'path'

### ISSUE THREAD

**Issue by cybertk** [fabioz/PyDev.Debugger#127]
Failed to run pydevd v1.4.0 from command line, full error is shown below

```
pydevd --port 20010 --client debug-server --file /opt/to/script
warning: Debugger speedups using cython not found. Run '"/usr/bin/python" "/usr/local/lib/python2.7/dist-packages/setup_cython.py" build_ext --inplace' to build.
Traceback (most recent call last):
  File "/usr/local/bin/pydevd", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/pydevd.py", line 1752, in main
    debugger.connect(host, port)
  File "/usr/local/lib/python2.7/dist-packages/pydevd.py", line 1050, in run
    if sys.path[0] != '' and m is not None and m.__file__.startswith(sys.path[0]):
AttributeError: 'NoneType' object has no attribute 'path'
```

**Comment by fabioz** [comment]
Can you reproduce this reliably?

**Comment by cybertk** [comment]
@fabioz  It's 100% reproducible with the given command, the Debug Server is PyCharm Professional 2018.1.4
