### ISSUE TITLE
RecursionError while setting matplotlib backend

### ISSUE THREAD

**Issue by szymonk211** [fabioz/PyDev.Debugger#148]
In Pycharm ipython console with attached debuger:
```python
import matplotlib  
matplotlib.use("TkAgg")
```
causes import error:

Traceback (most recent call last):
  File "/home/greensort/miniconda2/envs/borowka_fix/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-16f33be89508>", line 1, in <module>
    matplotlib.use("TkAgg")
  File "/home/greensort/pycharm-community-2019.1.1/helpers/pydev/pydev_ipython/matplotlibtools.py", line 70, in patched_use
    matplotlib.real_use(*args, **kwargs)
  File "/home/greensort/pycharm-community-2019.1.1/helpers/pydev/pydev_ipython/matplotlibtools.py", line 70, in patched_use
    matplotlib.real_use(*args, **kwargs)
  File "/home/greensort/pycharm-community-2019.1.1/helpers/pydev/pydev_ipython/matplotlibtools.py", line 70, in patched_use
    matplotlib.real_use(*args, **kwargs)
  [Previous line repeated 2982 more times]
RecursionError: maximum recursion depth exceeded

**Comment by floyebolu** [comment]
I'm also having a similar issue.
It appears what is happening is that ``matplotlib.real_use`` is being overwritten with ``patched_use`` on some subsequent call which leads to an infinite loop.

My intuition is that a fix would involve changing these lines:
https://github.com/fabioz/PyDev.Debugger/blob/fb6d3306fb2daba6a16642eae67e21a1e0dc83de/pydev_ipython/matplotlibtools.py#L75-L76
to:

```python
try:
    matplotlib.real_use
except AttributeError:
    matplotlib.real_use = matplotlib.use
finally:
   matplotlib.use = patched_use
```
The try-block is to catch if the ``real_use`` attribute exists or not. If it already exists it won't be overwritten.

**Comment by davisidarta** [comment]
I'm also having this issue. Any progress on this?

**Comment by davisidarta** [comment]
Needed a full OS reinstall to solve the issue, since no other solution appeared. Everything working fine on Ubuntu 20.
