### ISSUE TITLE
Adapter cannot be started if `sys.executable` isn't pointing to a python executable

### ISSUE THREAD

**Issue by Felk** [fabioz/PyDev.Debugger#176]
In `server/api.py#listen` the adapter is started with a call to `Popen` with these arguments:
```python
adapter_args = [
    sys.executable,
    os.path.dirname(adapter.__file__),
    "--for-server",
    str(endpoints_port),
    "--host",
    host,
    "--port",
    str(port),
    "--server-access-token",
    server_access_token,
]
```

However, python makes no guarantee that `sys.executable` will actually be pointing to a python executable. From the [documentation](https://docs.python.org/3/library/sys.html#sys.executable):
> A string giving the absolute path of the executable binary for the Python interpreter, on systems where this makes sense. If Python is unable to retrieve the real path to its executable, `sys.executable` will be an empty string or `None`.

In my case I am attempting to debug python code that runs enbedded in another application. The issue manifests itself on this line:
```python
debugpy.listen(5678)
```
which will time out:
```python
Traceback (most recent call last):
  File "D:\MyApplicationEmbeddingPython\debugpy\server\api.py", line 215, in listen
    sock, _ = endpoints_listener.accept()
  File "socket.py", line 292, in accept
socket.timeout: timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\MyApplicationEmbeddingPython\testscript.py", line 10, in <module>
    debugpy.listen(5678)
  File "D:\MyApplicationEmbeddingPython\debugpy\__init__.py", line 113, in listen
    return api.listen(address)
  File "D:\MyApplicationEmbeddingPython\debugpy\server\api.py", line 141, in debug
    log.reraise_exception("{0}() failed:", func.__name__, level="info")
  File "D:\MyApplicationEmbeddingPython\debugpy\server\api.py", line 139, in debug
    return func(address, settrace_kwargs, **kwargs)
  File "D:\MyApplicationEmbeddingPython\debugpy\server\api.py", line 228, in listen
    raise RuntimeError("timed out waiting for adapter to connect")
RuntimeError: timed out waiting for adapter to connect
```

If I manually replace `sys.executable` with a hardcode path like `"C:/Program Files/Python38/python.exe"` the adapter can successfully be launched and I can connect to the debugger.

**Comment by Felk** [comment]
I absolutely posted this to the wrong repository, oops! Meant to open an issue over at https://github.com/microsoft/debugpy/issues
