### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'line_to_offset'

### ISSUE THREAD

**Issue by mangopipeline** [fabioz/PyDev.Debugger#181]
I'm getting this strange error.

pydevd versoin 1.9.2
python version 3.7.2

on windows 10

it seems to be particularly mad at me using builtins.__import__ ()

i don't get this error in python 2.7 with pydev 1.8.0

Any ideas?
```
Traceback (most recent call last):
  File "_pydevd_frame_eval/pydevd_frame_evaluator.pyx", line 234, in _pydevd_frame_eval.pydevd_frame_evaluator.get_func_code_info
  File "C:\Projects\TechArt_Global\_BETH_TOOLS\LIBS\PyTools\btools\apps\utilities\py_debug_helper\pydev_source\3.7\_pydevd_frame_eval\pydevd_modify_bytecode.py", line 250, in insert_code
    if not code_line_info.line_to_offset:
AttributeError: 'tuple' object has no attribute 'line_to_offset'
```

**Comment by mangopipeline** [comment]
fyi i switch to pydevd 1.8.0 for python 3.7 and that seems to work good now.

**Comment by fabioz** [comment]
I'm in the process of releasing pydevd 2.0.0 and all the code related to breakpoints through bytecode modification was redone to use a different approach (so, closing this issue).

Please report back if you have any issue with 2.0.0.
