### ISSUE TITLE
ImportError: cannot import name 'fsnotify' from '_pydev_bundle'

### ISSUE THREAD

**Issue by zayfod** [fabioz/PyDev.Debugger#196]
Started seeing the following error when installing v2.4.0 with pip:

```
support@gifted-roentgen-master:~$ sudo pip install pydevd
Collecting pydevd
  Downloading https://files.pythonhosted.org/packages/0d/24/f8bae79a2a7d323fde6cb95d2ef8ddab9614321cdf1ee937c23489e76ead/pydevd-2.4.0.tar.gz (1.1MB)
     |████████████████████████████████| 1.1MB 6.0MB/s
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-u7c775z9/pydevd/setup.py", line 53, in <module>
        import pydevd
      File "/tmp/pip-install-u7c775z9/pydevd/pydevd.py", line 70, in <module>
        from _pydevd_bundle.pydevd_comm import (InternalThreadCommand, InternalThreadCommandForAnyThread,
      File "/tmp/pip-install-u7c775z9/pydevd/_pydevd_bundle/pydevd_comm.py", line 110, in <module>
        from _pydev_bundle import pydev_log, fsnotify
    ImportError: cannot import name 'fsnotify' from '_pydev_bundle' (/tmp/pip-install-u7c775z9/pydevd/_pydev_bundle/__init__.py)
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-u7c775z9/pydevd/
```

I see that `fsnotify` was added to `_pydev_bundle` in v2.4.0.

Environment:

```
support@gifted-roentgen-master:~$ python --version
Python 3.7.3

support@gifted-roentgen-master:~$ pip --version
pip 19.1.1 from ***/venv/lib/python3.7/site-packages/pip (python 3.7)
```

Reproduced on Ubuntu 16.04 LTS and 18.04 LTS.

**Comment by elapouya** [comment]
I confirm I have the same problem on Ubuntu 18.04 LTS

**Comment by fabioz** [comment]
It seems that the issue is that the package wasn't declared on `setup.py`. I've just fixed that in https://github.com/fabioz/PyDev.Debugger/commit/383723fb5e2bfd98e2f708fbf80e9507db5a1f36 and pushed a new version (2.4.1).
