### ISSUE TITLE
Can't attach debugger on native arm64 macOS machines

### ISSUE THREAD

**Issue by CCP-Lease** [fabioz/PyDev.Debugger#200]
Trying to attach a debugger on native arm64 macOS fails due to pydevd_tracing.py trying to load the x86_64 version of the attach dylib.

I get the following error:
```
Traceback (most recent call last):
  File "pydevd_tracing.py", line 145, in load_python_helper_lib
    lib = ctypes.pydll.LoadLibrary(filename)
  File "ctypes/__init__.py", line 431, in LoadLibrary
    return self._dlltype(name)
  File "ctypes/__init__.py", line 353, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(pydevd_attach_to_process/attach_x86_64.dylib, 6): no suitable image found.  Did find:
	pydevd_attach_to_process/attach_x86_64.dylib: mach-o, but wrong architecture
```

**Comment by gy-mate** [comment]
It works for me now on an Apple silicon Mac with PyCharm. This might be closed.

**Comment by gy-mate** [comment]
@fabioz or @CCP-Lease: could you please close this issue?

**Comment by fabioz** [comment]
It seems to be fixed in the pycharm fork, but it's still not upstream yet...
