### ISSUE TITLE
Getting `SyntaxError: invalid syntax` on version 2.9.0

### ISSUE THREAD

**Issue by yuvalta** [fabioz/PyDev.Debugger#230]
Hi, my Jenkins job failed because of the error below - 

```
09:15:45   Downloading pydevd-2.9.0.tar.gz (1.1 MB)
09:15:46 [91m    ERROR: Command errored out with exit status 1:
09:15:46      command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-kfHtSf/pydevd/setup.py'"'"'; __file__='"'"'/tmp/pip-install-kfHtSf/pydevd/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-AVycuK
09:15:46          cwd: /tmp/pip-install-kfHtSf/pydevd/
09:15:46     Complete output (8 lines):
09:15:46     Traceback (most recent call last):
09:15:46       File "<string>", line 1, in <module>
09:15:46       File "/tmp/pip-install-kfHtSf/pydevd/setup.py", line 53, in <module>
09:15:46         import pydevd
09:15:46       File "pydevd.py", line 3241
09:15:46         def log_to(log_file:str, log_level=3) -> None:
09:15:46                            ^
09:15:46     SyntaxError: invalid syntax
09:15:46     ----------------------------------------
```

Had to fix `pydevd` version to 2.8.0.

**Comment by fabioz** [comment]
It seems you're not on Python 3.

`pydevd` no longer supports Python 2 (if you need Python 2, then yes, please stick to pydevd 2.8.0).

**Comment by fabioz** [comment]
As a note, the metadata on the release was really wrong -- it wasn't saying that only Python 3.6 onwards was supported (so, I yanked 2.9.0 from Pypi and provided a 2.9.1 release with the proper metadata).

**Comment by yuvalta** [comment]
Thanks
