### ISSUE TITLE
Exception with Jython

### ISSUE THREAD

**Issue by Elizaveta239** [fabioz/PyDev.Debugger#40]
Exception appears when running with Jython:
```
Traceback (most recent call last):
  File "/home/user/work/ultimate/out/classes/production/python-helpers/pydev/pydevd.py", line 22, in <module>
    from _pydevd_bundle.pydevd_additional_thread_info import PyDBAdditionalThreadInfo
  File "/home/user/work/ultimate/out/classes/production/python-helpers/pydev/_pydevd_bundle/pydevd_additional_thread_info.py", line 17, in <module>
    from _pydevd_bundle.pydevd_cython_wrapper import PyDBAdditionalThreadInfo
  File "/home/user/work/ultimate/out/classes/production/python-helpers/pydev/_pydevd_bundle/pydevd_additional_thread_info.py", line 17, in <module>
    from _pydevd_bundle.pydevd_cython_wrapper import PyDBAdditionalThreadInfo
  File "/home/user/work/ultimate/out/classes/production/python-helpers/pydev/_pydevd_bundle/pydevd_cython_wrapper.py", line 7, in <module>
    is_python_64bit = (struct.calcsize('P') == 8)
  File "/home/user/work/ultimate/out/classes/production/python-helpers/pydev/_pydevd_bundle/pydevd_cython_wrapper.py", line 7, in <module>
    is_python_64bit = (struct.calcsize('P') == 8)
struct.error: bad char in struct format
```

**Comment by fabioz** [comment]
Will take a look at it.

**Comment by fabioz** [comment]
Fixed at: https://github.com/fabioz/PyDev.Debugger/commit/cbdfde8c546ba3f4c8f992feb96f238e3bd867d9
