### ISSUE TITLE
unable to set debugger, problem with pydevd_additional_thread_info_regular.py

### ISSUE THREAD

**Issue by anatheilper** [fabioz/PyDev.Debugger#51]
Hi,
I"m trying to activate the remote debugger. I tried with python 2.7.2 and also with python 2.6.5.

the trace that I get is the following:
Traceback (most recent call last):
  File "scripts/GenTest.py", line 2766, in <module>
    pydevd.settrace("10.185.36.3")
  File "/nfs/iil/proj/mpgarch/skl_gfx_aubs/ANATH/pydevd/pydevd.py", line 1127, in settrace
    patch_multiprocessing,
  File "/nfs/iil/proj/mpgarch/skl_gfx_aubs/ANATH/pydevd/pydevd.py", line 1209, in _locked_settrace
    debugger.set_tracing_for_untraced_contexts(ignore_frame=get_frame(), overwrite_prev_trace=overwrite_prev_trace)
  File "/nfs/iil/proj/mpgarch/skl_gfx_aubs/ANATH/pydevd/pydevd.py", line 528, in set_tracing_for_untraced_contexts
    for frame in additional_info.iter_frames(t):
  File "/nfs/iil/proj/mpgarch/skl_gfx_aubs/ANATH/pydevd/_pydevd_bundle/pydevd_additional_thread_info_regular.py", line 71, in iter_frames
    v = current_frames.get(t.ident)
**AttributeError: '_MainThread' object has no attribute 'ident'**

**Comment by fitermay** [comment]
Are you sure that the remote interpreter is py 2.6 or newer?
